// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsMg0mXxevmFdPlVH6ilvymdryJWpU9pk',
    appId: '1:6523279108:web:2b953ffbc22b272a6b2251',
    messagingSenderId: '6523279108',
    projectId: 'communion-table-talks',
    authDomain: 'communion-table-talks.firebaseapp.com',
    storageBucket: 'communion-table-talks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlXk7_KMaKxjFmCYeOWxnAtXVVMfIyYcc',
    appId: '1:6523279108:android:7a99b66d4f4ff2676b2251',
    messagingSenderId: '6523279108',
    projectId: 'communion-table-talks',
    storageBucket: 'communion-table-talks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHlSvxWbZBuXm9T8yrnV0zhgftXwx9qns',
    appId: '1:6523279108:ios:81d8b6db7df1ff556b2251',
    messagingSenderId: '6523279108',
    projectId: 'communion-table-talks',
    storageBucket: 'communion-table-talks.firebasestorage.app',
    iosBundleId: 'com.example.communionTableTalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHlSvxWbZBuXm9T8yrnV0zhgftXwx9qns',
    appId: '1:6523279108:ios:81d8b6db7df1ff556b2251',
    messagingSenderId: '6523279108',
    projectId: 'communion-table-talks',
    storageBucket: 'communion-table-talks.firebasestorage.app',
    iosBundleId: 'com.example.communionTableTalks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsMg0mXxevmFdPlVH6ilvymdryJWpU9pk',
    appId: '1:6523279108:web:2dd117d8b631a8446b2251',
    messagingSenderId: '6523279108',
    projectId: 'communion-table-talks',
    authDomain: 'communion-table-talks.firebaseapp.com',
    storageBucket: 'communion-table-talks.firebasestorage.app',
  );
}
